#################
##             ##
## UnitedUtils ##
##             ##
#################

##############
# Explosions #
##############

# This section covers all the explosion tweaks for PvP.

end-crystals:
# Toggle on or off vanilla crystal behaviour.
  nerf-crystal-damage: true
# The damage the crystal will do, in %. 0 will do no damage, 50 will do half damage, and 100 will do full damage.
  crystal-damage-percent: 0

###########
# Portals #
###########

# This section covers behaviours related to portals

nether-portals:
  # List of worlds for the plugin to deny Nether portal creation.
  blacklisted-worlds:
    - world_earth

portal-mapping:
  # Groups of linked overworlds and corresponding dimensions. Multiple groups are supported, but they must each have a defined overworld, nether, and end.
  world_resource:
    nether: world_nether
    end: world_the_end

spawn-portal:
# Settings for the portal at spawn.
  world: "world"
  corner1:
    x: 1106
    y: 45
    z: 997
  corner2:
    x: 1111
    y: 38
    z: 997
  command: "warps"

####################
# Void Protections #
####################

# Settings for void protection.

void-protections:
  # List of worlds for the plugin to function in. Leave empty to disable.
  whitelisted-worlds:
    - world
  # What y level to protect under, include one decimal space (Default: -64.0).
  void-threshold: -64.0

####################
# Random teleport  #
####################

# Settings for the /rtp command.

ul-rtp:
  use-economy: true
  max-attempts: 20
  cooldown: 5

  # List of worlds with rtp support. Missing worlds have rtp disabled automatically.
  worlds:
    world_earth:
      cost: 0
      zones:
        europe:
          min-x: 720
          max-x: 4000
          min-z: -11000
          max-z: -9200
        africa:
          min-x: 1000
          max-x: 7000
          min-z: -4600
          max-z: 1000
        asia:
          min-x: 15000
          max-x: 23000
          min-z: -8500
          max-z: -3500
        north_america:
          min-x: -24000
          max-x: -16000
          min-z: -11000
          max-z: -6000
        south_america:
          min-x: -14000
          max-x: -9500
          min-z: 0
          max-z: 6500
        oceania:
          min-x: 24000
          max-x: 31000
          min-z: 3500
          max-z: 6500
        antarctica:
          min-x: -30000
          max-x: 36000
          min-z: 15000
          max-z: 18000
        india:
          min-x: 14500
          max-x: 17500
          min-z: -6000
          max-z: -3000
        middle_east:
          min-x: 8000
          max-x: 12000
          min-z: -7800
          max-z: -3200
    world_nether:
      cost: 100
      zones:
        default:
          min-x: -14500
          max-x: 14500
          min-z: -14500
          max-z: 14500
    world_resource:
      cost: 100
      zones:
        default:
          min-x: -14500
          max-x: 14500
          min-z: -14500
          max-z: 14500

############
# Language #
############

# This section has editable language configurations for plugin messages.

messages:
  reload: "§c§lU§f§lL §7§lCore §8§l» §2Plugin reloaded."
  no-permission: "§c§lU§f§lL §7§lCore §8§l» §2You don't have permission to perform this command."
  invalid-command: "§c§lU§f§lL §7§lCore §8§l» §cInvalid command usage."
  void-protect: "§c§lU§f§lL §7§lCore §8§l» §cBe more careful! Sending back to spawn."
  nether-portal-deny: "§c§lU§f§lL §7§lCore §8§l» §cNether Portals are disabled on this world. Use the §8/warp §cmenu."
  map:
    - "§7§m────────────§7[ §c§lMAP §7]§7§m────────────"
    - "               §chttps://map.unitedlands.org"
    - "§7§m────────────────────────────"
  discord:
    - "§7§m────────────§7[ §c§lDISCORD §7]§7§m────────────"
    - "            §chttps://discord.unitedlands.org"
    - "§7§m────────────────────────────"
  shop:
    - "§7§m────────────§7[ §c§lSHOP §7]§7§m────────────"
    - "               §chttps://shop.unitedlands.org"
    - "§7§m────────────────────────────"
  wiki:
    - "§7§m────────────§7[ §c§lWIKI §7]§7§m────────────"
    - "               §chttps://wiki.unitedlands.org"
    - "§7§m────────────────────────────"
  greylist:
    - '§7§m─────────────§7[ §c§lGREYLIST §7]§7§m────────────'
    - '§fTo apply for the §cGreylist§f just comment under both forums your §cusername§f, §cage§f, and §c1 reason why you love the server§f. You can get up to §6§l5,000G§f per accepted application!'
    - '§f'
    - '§c&lMinecraft Forums: &ehttps://www.minecraftforum.net/forums/servers-java-edition/pc-servers/3121386-united-lands-towny-earth-war'
    - '§f'
    - '§c§lPlanet Minecraft: &§https://www.planetminecraft.com/forums/minecraft/servers/united-lands-towny-earth-war-643354/'
    - '§7§m───────────────────────────────────'
  whoarewe:
    - '§c§m+|✦        §r§c§l[§f§l Who are we? §c§l]§c§m        |✦+'
    - '§7We are a towny earth server with a'
    - '§7friendly community and custom plugins!'
    - '§c§m+|✦                  +✦+                  |✦+'

  rtp:
    prefix: "§cU§fL RTP §8» "
    tp-start: "§7Finding safe random position, please be patient..."
    tp-costs: "§7Paying random teleportation costs..."
    tp-end: "§7Successfully teleported to random position."
    error-rtp-disabled: "§eRandom teleportation is disabled in this world."
    error-no-world: "§cThe requested world does not exist."
    error-no-zones: "§cThere are no places to teleport to in this world."
    error-no-zone: "§cThe requested zone does not exist."
    error-no-block: "§eCould not find a safe block to teleport to within allowed time, please try again."
    warning-active-tp: "§eYou are already teleporting. Please wait for the current search to finish."
    warning-cooldown: "§eYou are on cooldown."
    warning-cooldown-elapsed: "§eHigh server load, waiting for cooldown to be reset. Give us a moment..."
    warning-nomoney: "§eYou cannot afford to random teleport."
