#################
##             ##
## UnitedUtils ##
##             ##
#################

##############
# Explosions #
##############

# This section covers all the explosion tweaks for PvP.

end-crystals:
# Toggle on or off vanilla crystal behaviour.
  nerf-crystal-damage: true
# The damage the crystal will do, in %. 0 will do no damage, 50 will do half damage, and 100 will do full damage.
  crystal-damage-percent: 0

############
# Language #
############

# This section has editable language configurations for plugin messages.

messages:
  reload: "§c§lU§f§lL §7§lCore §8§l» §2Plugin reloaded."
  no-permission: "§c§lU§f§lL §7§lCore §8§l» §2You don't have permission to perform this command."
  invalid-command: "§c§lU§f§lL §7§lCore §8§l» §cInvalid command usage."