name: UnitedUtils
version: '${project.version}'
main: org.unitedlands.unitedUtils.UnitedUtils
api-version: '1.21'
authors: [Litning11]
description: A plugin with miscellaneous utilities for United Lands
depend:
  - Towny
  - MapTowny
  - Vault
softdepend:
  - TownyFlight
commands:
  unitedutils:
    description: Reloads the plugin config.
    usage: /unitedutils reload
    permission: united.utils.admin
  remskill:
    description: Console script for removing a skill.
    usage: /remskill [Player Name] [Skill Name]
    permission: united.utils.admin
  map:
    description: Displays the map link.
    usage: /map
    permission: united.utils.player
  discord:
    description: Displays the Discord link.
    usage: /discord
    permission: united.utils.player
  wiki:
    description: Displays the wiki link.
    usage: /wiki
    permission: united.utils.player
  shop:
    description: Displays the shop link.
    usage: /shop
    permission: united.utils.player
  greylist:
    description: Displays the greylist links.
    usage: /greylist
    permission: united.utils.player
  whoarewe:
    description: Tells players who we are.
    usage: /whoarewe
    permission: united.utils.admin
  sb:
    description: Open the sidebar.
    usage: /sb
    permission: united.utils.player
  rtp:
    description: Random teleport function.
    usage: /rtp
  