#################
##             ##
## UnitedUtils ##
##             ##
#################

##############
# Explosions #
##############

# This section covers all the explosion tweaks for PvP.

end-crystals:
# Toggle on or off vanilla crystal behaviour.
  nerf-crystal-damage: true
# The damage the crystal will do, in %. 0 will do no damage, 50 will do half damage, and 100 will do full damage.
  crystal-damage-percent: 0

##################
# Nether Portals #
##################

# This section covers behaviours related to Nether Portals

nether-portals:
  # List of worlds for the plugin to deny Nether Portal creation.
  blacklisted-worlds:
    - world_earth

####################
# Void Protections #
####################

# Settings for void protection.

void-protections:
  # List of worlds for the plugin to function in. Leave empty to disable.
  whitelisted-worlds:
    - world
  # What y level to protect under, include one decimal space (Default: -64.0).
  void-threshold: -64.0

############
# Language #
############

# This section has editable language configurations for plugin messages.

messages:
  reload: "§c§lU§f§lL §7§lCore §8§l» §2Plugin reloaded."
  no-permission: "§c§lU§f§lL §7§lCore §8§l» §2You don't have permission to perform this command."
  invalid-command: "§c§lU§f§lL §7§lCore §8§l» §cInvalid command usage."
  void-protect: "§c§lU§f§lL §7§lCore §8§l» §cBe more careful! Sending back to spawn."
  portal-message: "§c§lU§f§lL §7§lCore §8§l» §cNether Portals are disabled on Earth. Use the §8/warp §cmenu. "
  map:
    - "§7§m────────────§7[ §c§lMAP §7]§7§m────────────"
    - "               §chttps://map.unitedlands.org"
    - "§7§m────────────────────────────"
  discord:
    - "§7§m────────────§7[ §c§lDISCORD §7]§7§m────────────"
    - "            §chttps://discord.unitedlands.org"
    - "§7§m────────────────────────────"
  shop:
    - "§7§m────────────§7[ §c§lSHOP §7]§7§m────────────"
    - "               §chttps://shop.unitedlands.org"
    - "§7§m────────────────────────────"
  wiki:
    - "§7§m────────────§7[ §c§lWIKI §7]§7§m────────────"
    - "               §chttps://wiki.unitedlands.org"
    - "§7§m────────────────────────────"
  greylist:
    - '§7§m─────────────§7[ §c§lGREYLIST §7]§7§m────────────'
    - '§fTo apply for the §cGreylist§f just comment under both forums your §cusername§f, §cage§f, and §c1 reason why you love the server§f. You can get up to §6§l5,000G§f per accepted application!'
    - '§f'
    - '§c&lMinecraft Forums: &ehttps://www.minecraftforum.net/forums/servers-java-edition/pc-servers/3121386-united-lands-towny-earth-war'
    - '§f'
    - '§c§lPlanet Minecraft: &§https://www.planetminecraft.com/forums/minecraft/servers/united-lands-towny-earth-war-643354/'
    - '§7§m───────────────────────────────────'
  toptime:
    - '§c§m+|✦                        §r§c§l[§f§lTop Playtime§c§l]§c§m                        |✦+'
    - '§f'
    - '§61. §f%cmi_playtimetop_name_1% - §c%cmi_playtimetop_time_1%'
    - '§62. §f%cmi_playtimetop_name_2% - §c%cmi_playtimetop_time_2%'
    - '§63. §f%cmi_playtimetop_name_3% - §c%cmi_playtimetop_time_3%'
    - '§64. §f%cmi_playtimetop_name_4% - §c%cmi_playtimetop_time_4%'
    - '§65. §f%cmi_playtimetop_name_5% - §c%cmi_playtimetop_time_5%'
    - '§66. §f%cmi_playtimetop_name_6% - §c%cmi_playtimetop_time_6%'
    - '§67. §f%cmi_playtimetop_name_7% - §c%cmi_playtimetop_time_7%'
    - '§68. §f%cmi_playtimetop_name_8% - §c%cmi_playtimetop_time_8%'
    - '§69. §f%cmi_playtimetop_name_9% - §c%cmi_playtimetop_time_9%'
    - '§610. §f%cmi_playtimetop_name_10% - §c%cmi_playtimetop_time_10%'
    - '§f'
    - '§c§m+|✦                                                |✦+'
  whoarewe:
    - '§c§m+|✦        §r§c§l[§f§l Who are we? §c§l]§c§m        |✦+'
    - '§7We are a towny earth server with a'
    - '§7friendly community and custom plugins!'
    - '§c§m+|✦                  +✦+                  |✦+'