#################
##             ##
## UnitedUtils ##
##             ##
#################

##############
# Explosions #
##############

# This section covers all the explosion tweaks for PvP.

nerf-crystal-damage: true
